"""共通Turn・Action・Event契約の初期スキーマ。"""
from alembic import op

revision = "0001_initial_contract"
down_revision = None
branch_labels = None
depends_on = None

DDL = r"""
CREATE TABLE campaigns (id uuid PRIMARY KEY, status text NOT NULL DEFAULT 'active' CHECK(status IN ('active','archived')), state_version bigint NOT NULL DEFAULT 0 CHECK(state_version>=0), event_sequence bigint NOT NULL DEFAULT 0 CHECK(event_sequence>=0), ruleset_version text NOT NULL CHECK(length(ruleset_version)>0), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE campaign_members (campaign_id uuid NOT NULL REFERENCES campaigns(id), principal_id uuid NOT NULL, role text NOT NULL CHECK(role IN ('player','gm')), active boolean NOT NULL DEFAULT true, PRIMARY KEY(campaign_id,principal_id));
CREATE TABLE entities (id uuid PRIMARY KEY, campaign_id uuid NOT NULL REFERENCES campaigns(id), kind text NOT NULL CHECK(kind IN ('pc','npc','item','object')), controller_id uuid, archived_at timestamptz, UNIQUE(campaign_id,id), FOREIGN KEY(campaign_id,controller_id) REFERENCES campaign_members(campaign_id,principal_id));
CREATE TABLE scenes (id uuid PRIMARY KEY, campaign_id uuid NOT NULL REFERENCES campaigns(id), sequence bigint NOT NULL CHECK(sequence>0), status text NOT NULL CHECK(status IN ('planned','active','closed')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(campaign_id,id), UNIQUE(campaign_id,sequence));
CREATE UNIQUE INDEX one_active_scene ON scenes(campaign_id) WHERE status='active';
CREATE TABLE turns (id uuid PRIMARY KEY, campaign_id uuid NOT NULL REFERENCES campaigns(id), scene_id uuid NOT NULL, request_id uuid NOT NULL, created_by uuid NOT NULL, actor_id uuid NOT NULL, input_schema_version integer NOT NULL DEFAULT 1 CHECK(input_schema_version>0), input_payload jsonb NOT NULL CHECK(jsonb_typeof(input_payload)='object'), request_hash bytea NOT NULL CHECK(octet_length(request_hash)=32), input_kind text NOT NULL CHECK(input_kind IN ('text','choice')), input_text text, selected_choice_id uuid, expected_state_version bigint NOT NULL CHECK(expected_state_version>=0), committed_state_version bigint CHECK(committed_state_version>=0), route text CHECK(route IN ('narrative','mechanical')), resolution_status text NOT NULL DEFAULT 'pending' CHECK(resolution_status IN ('pending','resolving','committed','not_applied','failed')), narration_status text NOT NULL DEFAULT 'pending' CHECK(narration_status IN ('pending','generating','completed','fallback')), max_actions integer NOT NULL DEFAULT 3 CHECK(max_actions>0), llm_call_count integer NOT NULL DEFAULT 0 CHECK(llm_call_count BETWEEN 0 AND 3), worker_epoch bigint NOT NULL DEFAULT 0 CHECK(worker_epoch>=0), lease_until timestamptz, committed_at timestamptz, narration text, narration_input jsonb CHECK(jsonb_typeof(narration_input)='object'), recovery_reason text CHECK(recovery_reason IN ('MODEL_TIMEOUT','INVALID_OUTPUT','MODEL_REFUSAL','INJECTION_DETECTED','CONTEXT_CONFLICT','UNKNOWN')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(campaign_id,created_by,request_id), UNIQUE(campaign_id,id), UNIQUE(campaign_id,scene_id,id), FOREIGN KEY(campaign_id,scene_id) REFERENCES scenes(campaign_id,id), FOREIGN KEY(campaign_id,created_by) REFERENCES campaign_members(campaign_id,principal_id), FOREIGN KEY(campaign_id,actor_id) REFERENCES entities(campaign_id,id), CHECK((input_kind='text' AND input_text IS NOT NULL AND length(input_text) BETWEEN 1 AND 8000 AND selected_choice_id IS NULL) OR (input_kind='choice' AND input_text IS NULL AND selected_choice_id IS NOT NULL)), CHECK((resolution_status='committed')=(committed_state_version IS NOT NULL)), CHECK((resolution_status='committed')=(committed_at IS NOT NULL)), CHECK(resolution_status<>'committed' OR route IS NOT NULL), CHECK(route IS DISTINCT FROM 'narrative' OR llm_call_count<=1), CHECK((narration_status IN ('completed','fallback'))=(narration IS NOT NULL)), CHECK(narration IS NULL OR length(narration) BETWEEN 1 AND 12000), CHECK((narration_status='fallback')=(recovery_reason IS NOT NULL)));
CREATE UNIQUE INDEX one_unresolved_turn ON turns(campaign_id) WHERE resolution_status IN ('pending','resolving');
CREATE INDEX turns_scene_history ON turns(campaign_id,scene_id,created_at,id);
CREATE TABLE turn_choices (id uuid PRIMARY KEY, campaign_id uuid NOT NULL, scene_id uuid NOT NULL, source_turn_id uuid NOT NULL, actor_id uuid NOT NULL, ordinal integer NOT NULL CHECK(ordinal BETWEEN 1 AND 5), label text NOT NULL CHECK(length(label) BETWEEN 1 AND 500), state_version bigint NOT NULL CHECK(state_version>=0), invalidated_at timestamptz, UNIQUE(source_turn_id,ordinal), UNIQUE(campaign_id,scene_id,actor_id,id), FOREIGN KEY(campaign_id,scene_id,source_turn_id) REFERENCES turns(campaign_id,scene_id,id), FOREIGN KEY(campaign_id,actor_id) REFERENCES entities(campaign_id,id));
ALTER TABLE turns ADD CONSTRAINT selected_choice_scope FOREIGN KEY(campaign_id,scene_id,actor_id,selected_choice_id) REFERENCES turn_choices(campaign_id,scene_id,actor_id,id);
CREATE TABLE actions (id uuid PRIMARY KEY, campaign_id uuid NOT NULL, turn_id uuid NOT NULL, ordinal integer NOT NULL CHECK(ordinal>0), actor_id uuid NOT NULL, kind text NOT NULL CHECK(kind IN ('attack','skill_check','use_item')), target_id uuid, item_id uuid, schema_version integer NOT NULL DEFAULT 1 CHECK(schema_version>0), command jsonb NOT NULL CHECK(jsonb_typeof(command)='object'), result jsonb NOT NULL CHECK(jsonb_typeof(result)='object'), result_kind text NOT NULL CHECK(result_kind IN ('applied','not_applicable')), ruleset_version text NOT NULL CHECK(length(ruleset_version)>0), UNIQUE(turn_id,ordinal), UNIQUE(campaign_id,turn_id,id), FOREIGN KEY(campaign_id,turn_id) REFERENCES turns(campaign_id,id), FOREIGN KEY(campaign_id,actor_id) REFERENCES entities(campaign_id,id), FOREIGN KEY(campaign_id,target_id) REFERENCES entities(campaign_id,id), FOREIGN KEY(campaign_id,item_id) REFERENCES entities(campaign_id,id), CHECK(kind<>'attack' OR target_id IS NOT NULL), CHECK(kind<>'use_item' OR item_id IS NOT NULL));
CREATE FUNCTION guard_action_insert() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE parent turns%ROWTYPE; BEGIN SELECT * INTO STRICT parent FROM turns WHERE id=NEW.turn_id FOR UPDATE; IF parent.resolution_status<>'committed' OR parent.route IS DISTINCT FROM 'mechanical' OR parent.campaign_id<>NEW.campaign_id OR parent.actor_id<>NEW.actor_id OR NEW.ordinal>parent.max_actions THEN RAISE EXCEPTION 'action violates committed turn contract'; END IF; RETURN NEW; END $$;
CREATE TRIGGER guard_action BEFORE INSERT ON actions FOR EACH ROW EXECUTE FUNCTION guard_action_insert();
CREATE TABLE events (id uuid PRIMARY KEY, campaign_id uuid NOT NULL REFERENCES campaigns(id), scene_id uuid, turn_id uuid, action_id uuid, sequence bigint NOT NULL CHECK(sequence>0), state_version bigint NOT NULL CHECK(state_version>=0), type text NOT NULL CHECK(length(type)>0), schema_version integer NOT NULL CHECK(schema_version>0), payload jsonb NOT NULL CHECK(jsonb_typeof(payload)='object'), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(campaign_id,sequence), FOREIGN KEY(campaign_id,scene_id) REFERENCES scenes(campaign_id,id), FOREIGN KEY(campaign_id,scene_id,turn_id) REFERENCES turns(campaign_id,scene_id,id), FOREIGN KEY(campaign_id,turn_id,action_id) REFERENCES actions(campaign_id,turn_id,id), CHECK(turn_id IS NULL OR scene_id IS NOT NULL), CHECK(action_id IS NULL OR turn_id IS NOT NULL));
CREATE INDEX events_turn ON events(campaign_id,turn_id,sequence) WHERE turn_id IS NOT NULL;
CREATE INDEX events_action ON events(action_id) WHERE action_id IS NOT NULL;
CREATE FUNCTION reject_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'history is append only'; END $$;
CREATE TRIGGER immutable_events BEFORE UPDATE OR DELETE ON events FOR EACH ROW EXECUTE FUNCTION reject_history_mutation();
CREATE TRIGGER immutable_actions BEFORE UPDATE OR DELETE ON actions FOR EACH ROW EXECUTE FUNCTION reject_history_mutation();
"""

def upgrade() -> None:
    op.execute(DDL)

def downgrade() -> None:
    op.execute("DROP TABLE events; DROP TRIGGER immutable_actions ON actions; DROP TRIGGER guard_action ON actions; DROP TABLE actions; DROP FUNCTION guard_action_insert(); DROP FUNCTION reject_history_mutation(); ALTER TABLE turns DROP CONSTRAINT selected_choice_scope; DROP TABLE turn_choices; DROP TABLE turns; DROP TABLE scenes; DROP TABLE entities; DROP TABLE campaign_members; DROP TABLE campaigns;")
